### ISSUE TITLE
Samller image, large image on hover

### ISSUE THREAD

**Issue by L0G1C** [L0G1C/Hipchat-MTG-Bot#8]
title says it all

**Comment by L0G1C** [comment]
This might not be possible because we need a strictly html solution?

**Comment by merlinjim** [comment]
I was wondering if JavaScript was allowed... There is a css way to do it I think...

On Apr 6, 2015 7:50 PM, Leo Jerez <notifications@github.com> wrote:

This might not be possible because we need a strictly html solution?

—
Reply to this email directly or view it on GitHub<https://github.com/L0G1C/Hipchat-MTG-Bot/issues/8#issuecomment-90289159>.

********************************************

Inmar Confidentiality Note:  This e-mail and any attachments are confidential and intended to be viewed and used solely by the intended recipient.  If you are not the intended recipient, be aware that any disclosure, dissemination, distribution, copying or use of this e-mail or any attachment is prohibited.  If you received this e-mail in error, please notify us immediately by returning it to the sender and delete this copy and all attachments from your system and destroy any printed copies.  Thank you for your cooperation.

Notice of Protected Rights:  The removal of any copyright, trademark, or proprietary legend contained in this e-mail or any attachment is prohibited without the express, written permission of Inmar, Inc.  Furthermore, the intended recipient must maintain all copyright notices, trademarks, and proprietary legends within this e-mail and any attachments in their original form and location if the e-mail or any attachments are reproduced, printed or distributed.

********************************************

**Comment by L0G1C** [comment]
Yeah there's some fancy css3 ways I saw but, wasn't sure if they would work. I can try.
